### ISSUE TITLE
Type hints & Hamcrest matchers

### ISSUE THREAD

**Issue by rowanhill** [hafriedlander/phockito#15]
Hi,

When stubbing a method, Hamcrest matchers cannot be used for parameters which have type hints. Attempting to do so raises an exception along the lines of:
`PHPUnit_Framework_Error : Argument 1 passed to __phockito_PhockitoHamcrestTest_MockMe_Mock::Baz() must be an instance of PhockitoHamcrestTest_PassMe, instance of Hamcrest_Core_IsInstanceOf given`

Is there a recommended work-around for this?

Thanks,
Rowan

**Comment by rowanhill** [comment]
I've made a proof-of-concept stab at how this could possibly be tackled: https://github.com/rowanhill/phockito/tree/typehints. It's pretty ugly, but it at least works in my use case. It basically subclasses the parameter's type and proxies a matcher. I've made it raise an error if the parameter's type already has methods on Hamcrest_Matcher, but I'm not sure if that's right or not.

I'm also not sure if something like this would belong here or in Hamcrest.

Do you have any thoughts? Hopefully you have a much neater way of doing this already. :)

**Comment by RichardBradley** [comment]
I like the patch in "typehints"; it's clever.
Some thoughts:
- You'll need to update the docs carefully to make this feature discoverable: it's not going to be that obvious to new users
- Methods can have "array" and "callable" as [parameter type hints](http://php.net/manual/en/language.oop5.typehinting.php). This approach won't work for that. Those methods will still be mockable only with literal parameter values.

**Comment by rowanhill** [comment]
Good points, thanks.

If the maintainers of this repo think this is a worthwhile approach, I might take a look at producing something a bit more complete.

**Comment by rowanhill** [comment]
@hafriedlander Do you have any comments on this? Would you be interested in a pull request along these lines?

**Comment by hafriedlander** [comment]
Hi,

Interesting problem, and cool solution. I see a couple of problems with it though. The first is that the syntax is ugly - not really a showstopper, but it'd be better if it wasn't. The second is that it won't work with "array" type hints, since you can't subclass arrays.

I'm wondering if we can just ignore the type hint errors. A quick test seems to imply that something like:

``` php
set_error_handler(function(){ /* NOP */ }, E_RECOVERABLE_ERROR);
```

will let you pass any argument into a type-hinted method without causing an error.

**Comment by hafriedlander** [comment]
See https://github.com/hafriedlander/phockito/tree/fix/typehints_and_hamcrest for a prototype (don't really like matching error text with regex, but works for me in PHP 5.4).

**Comment by hafriedlander** [comment]
Argh, that won't work. Or rather, it will, but set_error_handler doesn't chain, so calling Phockito::include_hamcrest breaks any existing error handler.

**Comment by rowanhill** [comment]
Yeah, setting the error handler feels surprising - I wouldn't expect a library to do that, and I suspect if it broke someone's code, it would be an irritating and confusing bug to track down.

Even with the limitations around "array" type hints, I think the proxy approach is what I'd prefer to see - do you agree?

I guess people would be left with three (less than ideal) choices if they try to use a hamcrest matcher with an array hinted param:
1. Alter their test to use an array of the exact value, rather than a matcher
2. Alter their production code to drop the type annotation
3. Add an error handler, as in your example

Do you have any other ideas for approaches? And if not, would you like me to carry on with my branch and submit a pull request?

**Comment by hafriedlander** [comment]
You can use the alternate when syntax, like `Phockito::when($mock)->foo(anything())->thenReturn(1)` instead of `Phockito::when($mock->foo(anything()))->thenReturn(1)`.

I'm happy for you to raise a pull request for type-coercion. I'd prefer it implemented in a slightly different manner though, if you'd like to consider it.

Instead of `createBridgeType` creating a class that tries to act like a Hamcrest matcher, it could just use Phockito::mock to create the subtype of the type hinted class. Then set a property on it (like __phockito_matcher) which contains the Hamcrest matcher. Finally in `Phockito#_arguments_match` check for that property and use it instead.

This has the advantage of being a smaller code change. Also because it's a mock, it's impossible to trigger any side-effects the original class might have if you accidentally pass the typecast item to a spy instead of a mock.

**Comment by hafriedlander** [comment]
And merged. Thanks.
