### ISSUE TITLE
Have mocked methods throw "notmocked" exceptions instead of returning null optionally

### ISSUE THREAD

**Issue by drdamour** [hafriedlander/phockito#21]
I see a lot of test fail silently because the methods on a mock return null automatically.  This can be attributed in a weakness to code, but it's difficult to discover such a weakness in the implementation.

What i propose is adding a second optional parameter to Phockito::mock that indicates that instead of returning null for all methods in a mock, instead some exception be thrown.  this would result in many tests failing loudly instead of failing silently.

thoughts?

**Comment by hafriedlander** [comment]
I'm not sure of why it would be desirable in the first place (are you trying to find an only partially specified stub? I'd need an example test to see the problem I think), but there's a technical reason why this wouldn't work

All the methods need to return null, because when you're specifying stubbed values, you're actually calling the mocked methods. For instance, this wouldn't work if the method `offsetGet` throws an exception:

``` php
Phockito::when($iterator->offsetGet(0))->return('first');
```

Because calling "$iterator->offsetGet(0)" actually gets called before calling Phockito::when with the result, and that would cause offsetGet to throw an exception.

**Comment by drdamour** [comment]
I see the problem you mention, that's unfortunate.

Many of the mock frameworks (rhino, moq) have a "Strict mode" and it can be very desirable to work within that strict mode.  as mentioned above, lots of code does stuff when a method returns null different than what may be expected.  

By putting the mock in strict mode you're forcing the test writer to make a decision about what should be returned to each invocation of a method on the dependency.  This causes them [hopefully] to think and write more specific tests (and more iterations where the results are different).  It's a philosophical thing, do you want your tests to be stricter (and more brital) to alert developers that they've made change...or do you prefer a looser implementation.

**Comment by drdamour** [comment]
So i thought about this a while, here's what i came up with.

Add a Phockito::setStrict($mock) method that sets the $mocked object to enter strict mode.  Thus you can do code like this:

```
$mock = Phockito::mock( "Dependency" );
Phockito::when( $mock->someDependencyMethod() )->return( $dummyValue);


$x = $mock->someDependencyMethod(); //returns $dummyValue
$y = $mock->someOtherMethod(); //returns null

Phockito::setStrict( $mock );

$x = $mock->someDependencyMethod(); //returns $dummyValue
$y = $mock->someOtherMethod(); //throws

```

It's an extra step in the tests to be sure, but now if someone was to write some code that requires that dependency and added a new method call existing test suite would fail explicitly instead of only possibly in case the coder wrote some bad code that didn't check for nulls.
