### ISSUE TITLE
AssertThat() already exists in later versions of PHPUnit

### ISSUE THREAD

**Issue by stojg** [hafriedlander/phockito#32]
While running some tests locally I stumbled into this error

```
 Fatal error: Cannot redeclare assertThat() (previously declared in /..../vendor/phpunit/phpunit/PHPUnit/Framework/Assert/Functions.php:1637) in /...../vendor/hafriedlander/phockito/hamcrest-php/hamcrest/Hamcrest.php on line 32
```

It seems like the latest version of phpunit has the same function in the global scope

https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Assert/Functions.php#L1671
as 
https://github.com/hafriedlander/phockito/blob/master/hamcrest-php/hamcrest/Hamcrest.php#L25

**Comment by srizzling** [comment]
Getting something similar like this today as well:

```
PHP Fatal error:  Cannot redeclare any() (previously declared in /var/www/html/cwp104/vendor/hafriedlander/phockito/hamcrest-php/hamcrest/Hamcrest.php:384) in /var/www/html/cwp104/vendor/phpunit/phpunit/PHPUnit/Framework/Assert/Functions.php on line 59‏
```

**Comment by chillu** [comment]
This was an issue when using PHPUnit 4.x as a PHAR apparently, and has been fixed with PHP 4.6.2 (https://github.com/sebastianbergmann/phpunit/issues/1667 and https://github.com/sebastianbergmann/phpunit/commit/2b463390e96f248db7bbddefe480028007bc0442).

The commit above limits the `require()` call of `Functions.php` to `autoload-dev`, which is a root-only composer property - so will be ignored when PHPUnit is required as a dependency (see https://getcomposer.org/doc/04-schema.md#files).

PHPUnit 3.x doesn't have this issue since it doesn't require `Functions.php` automatically anywhere.

So there's still a clash if you both call `Phockito::include_hamcrest()` and `require(<phpunit-path>/Functions.php)`, but that's OK - since they're both opt-in you can at least avoid those clashes.

**Comment by chillu** [comment]
Given the above, I would recommend to close this issue - other than removing the globals altogether, I don't know how to fix this within Phockito itself.

**Comment by hafriedlander** [comment]
Thanks @chillu. We could "fix" the issue if Functions is included first by checking for the function name and throwing a more useful warning, but if it's the other way around (Hamcrest included first) we can't, and that seems like the more common case. So closing.
