### ISSUE TITLE
Stubbing override

### ISSUE THREAD

**Issue by dagguh** [hafriedlander/phockito#5]
Only the first stubbing works.

when($mock->foo())->return(1);
when($mock->foo())->return(2);
when($mock->foo())->return(3);
$mock->foo(); // returns 1

It should return 3.

**Comment by hafriedlander** [comment]
Hi,

I'll have to re-check the Mockito docs, but I don't think that's right. What should happen is

when($mock->foo())->return(1);
when($mock->foo())->return(2);
when($mock->foo())->return(3);
$mock->foo(); // returns 1
$mock->foo(); // returns 2
$mock->foo(); // returns 3

That is, you can't ever overwrite a preset response, only add more to the sequence of responses.

**Comment by hafriedlander** [comment]
I couldn't see anything specifically related in the Mockito docs, but I've decided this is the way I want it to operate anyway. Calling return multiple times is the same as calling thenReturn.

There is a Phockito::reset method to forget stubbed responses, but as the Mockito docs say "Smart Mockito users hardly use this feature because they know it could be a sign of poor tests. Normally, you don't need to reset your mocks, just create new mocks for each test method."
