### ISSUE TITLE
Can't mock SoapClient

### ISSUE THREAD

**Issue by FredrikWendt** [hafriedlander/phockito#8]
This (currently) fails because of the reflection trying to get default values for arguments which - if I understand it correctly - comes from the fact that SoapClass is a native class (and the Reflection\* doesn't really work with that?).

**Comment by hafriedlander** [comment]
Fixed (sort of) in 1710ea4185121bca8c345a607eedad4250eafab9

We have to just assume the default argument is null, since we can't figure out what it should be. That should be fine for mocks, but might have side-effects in spies (if you don't specify a default argument, the spy will call the underlying method with null for that argument, which might do something other than expected).
